### ISSUE TITLE
Error in if (strand == 1) { : argument is of length zero

### ISSUE THREAD

**Issue by adbeggs** [im3sanger/dndscv#11]
Hi

I'm analysing a cohort of exome sequencing data using dndscv - I've done this fine before with no issues off WGS data, however when I run dndscv it crashes out with the error:

> Error in if (strand == 1) { : argument is of length zero

I've had a look at the code and I'm not sure how/why this is happening. I've done a sanity check on my input file and can't see any glaring errors, but I might be wrong - any suggestions?

Thanks

Andrew

**Comment by im3sanger** [comment]
Hi Andrew,

Thank you for your interest in dNdScv.

I have seen that error sometimes when only indels are fed to dndscv. Could this be the problem here? (Note that dndscv was primarily designed to work with substitutions and while it can also handle indels, dinucleotides and other complex changes, it expects to see coding substitutions too).

If this is not the problem, please send me a reproducible example and I will investigate this error.

Many thanks!
Inigo
