### ISSUE TITLE
No pglobal_cv and qglobal_cv in dndsout$sel_cv

### ISSUE THREAD

**Issue by kmtiny** [im3sanger/dndscv#12]
Hi,
I had ran dndscv with the mutations for 78 gastric carcinoma samples. However, no columns of pglobal_cv and qglobal_cv in the resulting file dndsout$sel_cv were found. Parts of results were followed as:

![image](https://user-images.githubusercontent.com/16219787/44963171-05439500-af5b-11e8-8b34-8c8d4f4ac7d7.png)

, and I don't know the reason why it occurs and hope to get helps from you! 

Best,
kaimin, Guo

**Comment by im3sanger** [comment]
Hello,

This is the correct output when running dndscv without indels. In the absence of indels, only substitutions are used and the global p- and q-values are shown in the "pallsubs_cv" and "qallsubs_cv" columns, respectively.

Best wishes,
Inigo

**Comment by im3sanger** [comment]
Hi again,

Actually, I just noticed the left side of your table, with genes like TTN and MUC16 having highly significant p-values despite showing numbers of synonymous, missense and nonsense substitutions consistent with neutral evolution. Other genes like ZFHX3 show 32 synonymous mutations and 2 missense, again reflecting serious problems with the mutation calls. The number of indels in some of the top genes also looks unreliable.

All of this is very odd and reflects problems with the data. Is it possible that you fed dndscv a mixture of targeted and exome/genome datasets rather than actual whole-exome or whole-genome data? Or that you have a serious problem of germline contamination? (this would be reflected by global dN/dS values <<1). The results look clearly wrong so if you tell me more about your design, I may be able to give you some better advice.

Inigo
