### ISSUE TITLE
Undefined column in running dndscv

### ISSUE THREAD

**Issue by beginner984** [im3sanger/dndscv#26]
Sorry,

This command always returns error

> signif_genes = sel_cv[sel_cv$qglobal_cv<0.1, c("gene_name","qglobal_cv")]
Error in `[.data.frame`(sel_cv, sel_cv$qglobal_cv < 0.1, c("gene_name",  : 
  undefined columns selected
> 
>

**Comment by im3sanger** [comment]
Hello,

I suspect that the reason for this is that you are not using indels in this analysis (or that you do not have enough of them to trigger the use of the indel model).

The key sentence in the tutorial is this one: "The global q-value integrating all mutation types are available in the qglobal_cv and qallsubs_cv columns for analyses with and without indels, respectively".

So, instead of the line above, you need to use:
signif_genes = sel_cv[sel_cv$qglobal_cv<0.1, c("gene_name","qglobal_cv")]

**Comment by beginner984** [comment]
Thanks a lot,

You absolutely right because I am analysing SNV and indel files separately. So may I must combine them

Thank you for being very responding
