### ISSUE TITLE
how to convert gff3 to cdsfile for buildref

### ISSUE THREAD

**Issue by q623928815** [im3sanger/dndscv#33]
I'm trying to calculate dN/dS within Populus and i have annotation file in gff3 format. I wanna know how to convert gff3 to fit buildref to build this reference. Thanks.

**Comment by im3sanger** [comment]
Hello,

Thanks for your interest in dNdScv. I have personally never used gff3 and I suspect that adapting it to serve as an input for buildref may depend on the exact columns that you have in the file, so it is hard for me to provide a specific answer. 

My advice would be that you try the examples in [this tutorial](http://htmlpreview.github.io/?http://github.com/im3sanger/dndscv/blob/master/vignettes/buildref.html). The input to buildref must be a tab-delimited file with the same columns shown in the first example of the tutorial. If you have all these entries in your gff3 file, you just need to reorder the columns and format the file so that it is structured as the example provided.

Alternatively, you could try generating an input file using Ensemble BioMart, as described in the tutorial. You can access BioMart Plants from the Ensembl page for Populus. Or, I think, using [this link](http://plants.ensembl.org/biomart/martview?VIRTUALSCHEMANAME=plants_mart&ATTRIBUTES=ptrichocarpa_eg_gene.default.feature_page.ensembl_gene_id|ptrichocarpa_eg_gene.default.feature_page.ensembl_transcript_id&FILTERS=&VISIBLEPANEL=attributepanel). Perhaps, since gff3 and BioMart are both supported by Ensemble, they may be able to provide more detailed advice.

I hope this helps,
Inigo
