### ISSUE TITLE
Error when using covariates

### ISSUE THREAD

**Issue by pablo-gar** [im3sanger/dndscv#4]
When I run
` dndscv(mutations)`

I get the following error:
```
Error in glm.fitter(x = X, y = Y, w = w, etastart = eta, offset = offset,  : 
  NA/NaN/Inf in 'x'
```

I don't get the error when I run:
` dndscv(mutations, cv = NULL)`

Any ideas on what's wrong?

**Comment by pablo-gar** [comment]
Thanks so much for your quick response! Here's a link to a mutation table that gives me this error.

https://drive.google.com/a/stanford.edu/file/d/15BcQBfYiSDeQGgAAKm5JFXL-sjmoM8J8/view?usp=sharing

Also I changed line 238 in dndscv/dndscv.R from:
```stop(sprintf('%0.0f mutations have a wrong reference base, please correct and rerun.',sum(!is.na(wrong_ref)))) # This can be made into a mere warning and the rest of the code will work```
To:
```warning(sprintf('%0.0f mutations have a wrong reference base, please correct and rerun.',sum(!is.na(wrong_ref)))) # This can be made into a mere warning and the rest of the code will work```

Is there a subset of  covariates that you'd recommend using instead of the entire matrix? I'm thinking trying to remove correlated covariates, or covariates that in your experience don't add to much to the model, or maybe covariates that biologically may not be as important?

Thanks again,
Pablo

**Comment by im3sanger** [comment]
Hi Pablo,

The 20 default covariates currently used by the package (hg19) are the first 20 principal components of 169 chromatin marks from the RoadMap Epigenomics Project. This includes data from 63 cell lines and 10 different epigenetic marks (H3K9me3, H3K36me3, H3K27me3, H3K4me1, H3K4me3, H3K9ac, H3K23ac, H3K14ac, H2AK9ac and DNase), to try to capture the variation in the epigenomic landscape across tissue types and chromatin marks.

Because the covariates are principal components, they are orthogonal and the first few principal components _tend_ to explain most of the variation. So you could use the "maxcov" argument to select the top covariates from the default matrix (e.g. maxcov=5 will use the first 5 principal components as covariates). One area of future development for dNdScv is data-driven model selection when fitting the regression model. If you are interested, you can see the performance of the regression model on your data using:

`summary(dndsout$nbreg)`

I hope it helps,
Inigo

**Comment by im3sanger** [comment]
Hi again,

I just had a quick look at the sample of mutations that you sent me. I always look at the theta parameter and the global dN/dS values for a first impression on the quality of a dataset. There seem to be some issues with your dataset. Using cv=NULL to run dndscv yields a very low theta (0.0053) and very low global dN/dS values (missense: 0.37, nonsense: 0.13).

Very low theta values (the overdispersion parameter of the negative binomial regression) indicate that the mutation rate varies too much across genes. Typical values for clean datasets of somatic mutations are normally >>1. Multiple problems can be behind this, including SNP contamination, recurrent artefacts, listing the same mutation multiple times when analysing related samples, kataegis or mutation clusters (every entry in the input table of mutation should be an independent mutation), etc. In your dataset, global dN/dS values are <<1, strongly suggesting a high rate of SNP contamination (assuming that these are somatic calls and not germline SNPs). Counting the number of synonymous mutations per gene can also help identify the source of the low theta value. Your sample dataset contains 3,974 coding mutations, which across ~20,000 genes would be expected to have a low density of mutations per gene. However, there are genes in your dataset with >100 synonymous mutations. Some of them are genes frequently affected by mapping artefacts (Martincorena et al, 2017). Although I do not know the nature of your data, if these are somatic calls, SNP filtering and using an unmatched normal panel to identify recurrent artefacts may be helpful.

I suspect that these issues are likely behind the error from glm.nb.

I hope it helps,
Inigo

```
dndsout$nbreg$theta
dndsout$globaldnds
head(sort(table(dndsout$annotmuts$gene[dndsout$annotmuts$impact=="Synonymous"]),decreasing=T),20)
```

**Comment by pablo-gar** [comment]
Thanks so much for your detailed response, it is very informative. I will take a closer look to the highly mutated genes, and I'll go over your paper to make sure I'm applying the right filters and controls. Thanks for explaining the covariates, I did not catch that they were the PCs -- it makes sense.

Pablo
