### ISSUE TITLE
'closure error' plz help me.

### ISSUE THREAD

**Issue by a00101** [im3sanger/dndscv#42]
> head(data)
  sampleID  chr       pos ref mut
1 NSLA_198 chr6  53507580   T   A
2 NSLA_198 chr1  24456220   C   T
3 NSLA_198 chr3  50159664   C   T
4 NSLA_198 chr7 150856517   C   T
5 NSLA_198 chr7 150858827   A   G
6 NSLA_198 chr7  43479738   T   C
> dndsout = dndscv(data, cv=Null, refdb = "DNDSCV/RefCDS_human_GRCh38.p12.rda")
[1] Loading the environment...
[2] Annotating the mutations...
    Note: 53 mutations removed for exceeding the limit of mutations per gene per sample (see the max_muts_per_gene_per_sample argument in dndscv)
[3] Estimating global rates...
[4] Running dNdSloc...
[5] Running dNdScv...
Error in covs[genemuts$gene_name, ] : 
  object of type 'closure' is not subsettable
In addition: Warning messages:
1: In dndscv(data, cv = Null, refdb = "DNDSCV/RefCDS_human_GRCh38.p12.rda") :
  Same mutations observed in different sampleIDs. Please verify that these are independent events and remove duplicates otherwise.
2: glm.fit: fitted rates numerically 0 occurred 
3: glm.fit: fitted rates numerically 0 occurred

**Comment by im3sanger** [comment]
Hello,

Apologies for the slow response, somehow I had missed this message until now. I have never encountered this error before. From the error message that you are getting, it could be that you need to specify "cv=NULL" in upper case, instead of "cv=Null".

If the above suggestion does not solve your problem, please reopen this issue and perhaps send me a small example dataset that I could use to reproduce and correct the error.

Many thanks and sorry again for the unacceptably slow response,
Inigo
