### ISSUE TITLE
Zero coding substitutions found in this dataset

### ISSUE THREAD

**Issue by huynguyen250896** [im3sanger/dndscv#43]
I have the data something like:

> sampleID | chr | pos | ref | mut
> 
> ENST00000447894 | 6 | 515 | G | T
> ENST00000338641 | 22 | 3 | G | T
> ENST00000335508 | 2 | 15 | A | T
> ...

and when run dndscv :
`dndsout = dndscv(mutations)`
I run into the problem:

> [1] Loading the environment...
> [2] Annotating the mutations...
> Error in dndscv(mutations) : 
>   Zero coding substitutions found in this dataset. Unable to run dndscv. Common causes for this error are inputting only indels or using chromosome names different to those in the reference database (e.g. chr1 vs 1)

please teach me the solution to solve it

**Comment by im3sanger** [comment]
Hello,

This error message appears when none of your point mutations map to coding regions, as defined by the RefCDS object. Please make sure that your input table contains coding mutations and double check that your chromosome names match those of the RefCDS object (e.g. for GRCh37/hg19 chromosome names are "1", "2"... "X","Y", but for the RefCDS object available for GRCh38 the correct names are "chr1", "chr2"... "chrX", "chrY", following Ensembl BioMart's format).

Looking at the example mutations provided in your question, I notice that your "sampleIDs" are Ensembl transcript IDs and it looks like the coordinates are relative to the transcript, not chromosomal coordinates. This is not a valid input to dNdScv with the default RefCDS (it would be valid if you use a custom RefCDS with transcripts instead of chromosomes). If you use the default RefCDS, you need to input mutations using chromosome coordinates (and the bases should correspond to those in the reference sequence).

I hope this helps,
Inigo
