### ISSUE TITLE
Number of Driver Mutations

### ISSUE THREAD

**Issue by md15799** [im3sanger/dndscv#6]
Hi, 

I am trying to replicate the method for finding the average number of driver mutations per tumour used in Universal Patterns of Selection in Cancer and Somatic Tissues. On my dataset of breast cancer donors the method below predicts 14 driver mutations which is significantly more than the 4 mutations estimated in your paper. So I think I must be doing something wrong. My interpretation of the method is:

For each gene:
f_m = (w_m - 1) / w_m for all w_m > 1
d_m = f_m * n_m

Then:
average_number_of_drivers_per_donor = sum(d_m) / num(samples)

I implemented it like this:

```
df <- read.csv(file="brca_us_dnds.tsv", header=FALSE, sep='\t')
dndsout = dndscv(df)
dndsout$new <- dndsout$sel_cv[which(dndsout$sel_cv$wmis_cv > 1),]
dndsout$new$f_mis<-((dndsout$new$wmis_cv - 1)/dndsout$new$wmis_cv)
dndsout$new$d_mis<-(dndsout$new$f_mis * dndsout$new$n_mis)
print(sum(dndsout$new$d_mis, na.rm = TRUE) / length(unique(dndsout$annotmuts$sampleID)))
```

This is my first program in R so please bear with me on some of the uglier aspects of this code snippet. For example, I'm sure there's an easier way to select only for wmis_cv > 1 without assigning it to a new table. I hope it's still fairly easy to see what I've done here.

Many Thanks,

Maddie

**Comment by im3sanger** [comment]
Hi Maddie,

Thanks for your interest in dNdScv.

That is not the correct way to do this calculation and it will lead to inflated estimates. The number of mutations per gene is limiting, which leads to large stochastic variation in dN/dS values per gene. If you select all genes that happen to have dN/dS>1 and calculate their average dN/dS value you will get a value >>1, even if you were using data simulated under neutrality.

The correct way of doing this calculation is using the global dN/dS estimates (calculated across all genes), which are provided in the `dndsout$globaldnds` output.

However, I want to warn users that global estimates of the number of driver mutations require an extremely careful handling of biases and SNP contamination (see the methods description of the paper). Even small biases introduced by modest SNP contamination or SNP overfiltering can lead to large errors in these estimates, which required a great deal of work in my paper (including recalling all the TCGA exomes and even building a separate dNdScv reference database excluding the sites removed in the unmatched normal panel). In general, these estimates are more reliable when restricting the analysis to a list of known cancer genes, since the signal to noise ratio is higher than at exome level. For example, with caution you could use the code below (or use your own favourite list of genes).

Best wishes,
Inigo

```
data("cancergenes_cgc81", package="dndscv")
dndsout = dndscv(mutations, gene_list=known_cancergenes)
wmis = pmax(1, as.matrix(dndsout$globaldnds[1,2:4]))
f_mis = (wmis-1)/wmis[1] # Using your variable names. This also includes the 95% confidence intervals.
d_mis = f_mis*sum(dndsout$sel_cv$n_mis)/num_samples # Note that "num_samples" should be all samples sequenced in the study, including those that did not have any mutation in the selected genes [i.e. the real number of samples can be higher than length(unique(dndsout$annotmuts$sampleID)) ]
```
