### ISSUE TITLE
A wrong parameter in substmodel "192r_3w"?

### ISSUE THREAD

**Issue by kakiuchi-kyt** [im3sanger/dndscv#70]
Dear Authors,

"dndscv" is an excellent package to calculate dN/dS value!

I found a possible error in the code.
The default sm parameter is "192r_3w", and dndscv function reads "submod_192r_3w.rda" which contain a table named "substmodel".
The table will be used to calculate the mutation rate. However, the last row of the table, which is for TTT>TGT substitution, has only "t", while other rows have "t*NNN>NNN".
I think the last row should be;
` TTT>TGT "t*TTT>TGT"         "t*TTT>TGT*wmis"         "t*TTT>TGT*wnon"         "t*TTT>TGT*wspl"`
instead of;
` TTT>TGT "t"         "t*wmis"         "t*wnon"         "t*wspl"`

Is this an error, or am I wrong?

Please let me know.

Sincerely,
Nobuyuki Kakiuchi

**Comment by im3sanger** [comment]
Hello Nobuyuki Kakiuchi,

Thank you for your message and your interest in dndscv.

I can confirm that this is not an error. The NNN>NNN rate parameters in the substitution model are relative rates, relative to one of them. TTT>TGT was arbitrarily chosen as reference and so has a fixed value of 1, which means that it can be excluded from the substitution matrix (in fact it needs to be excluded as otherwise there are more parameters than can be estimated from the data). In other words, if you are interested in the _absolute_ rate of TTT>TGT changes per TTT site, the value is "t". If you are interested in the absolute rate of any other trinucleotide change, the value is "t*NNN>NNN".

I hope this helps.

Best,
Inigo
